import { supabase, configured } from "./supabase";
import districtData from "../../server/data/districts.json";

export const configuredBackend = configured;

// ---- reports -----------------------------------------------------------

export async function getReports() {
  if (!configured) throw new Error("Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_KEY.");
  const { data, error } = await supabase
    .from("reports")
    .select("*")
    .order("created_at", { ascending: false });
  if (error) throw new Error(error.message);
  return data ?? [];
}

export async function setStatus(id, status) {
  const { data, error } = await supabase
    .from("reports")
    .update({ status })
    .eq("id", id)
    .select()
    .single();
  if (error) throw new Error(error.message);
  return data;
}

/**
 * Live queue. Replaces the server's SSE stream: Postgres pushes the change,
 * so a report filed from anywhere lands here without the Express server being
 * involved at all.
 */
export function subscribe({ onInsert, onUpdate, onStatus }) {
  if (!configured) return () => {};
  const channel = supabase
    .channel("reports-feed")
    .on("postgres_changes", { event: "INSERT", schema: "public", table: "reports" },
        (p) => onInsert?.(p.new))
    .on("postgres_changes", { event: "UPDATE", schema: "public", table: "reports" },
        (p) => onUpdate?.(p.new))
    .subscribe((s) => onStatus?.(s === "SUBSCRIBED"));
  return () => supabase.removeChannel(channel);
}

// ---- coverage ----------------------------------------------------------

// Bundled rather than fetched. It is regenerated by `npm run pull-data`, not by
// users, so shipping it with the build removes a network dependency and lets
// the board work with the Express server switched off.
export const districts = districtData;

// Real HRM council district names. The feed only carries "District 8", which
// tells a Public Works reader nothing.
export const DISTRICT_NAMES = {
  1: "Waverley–Fall River–Musquodoboit Valley",
  2: "Preston–Chezzetcook–Eastern Shore",
  3: "Dartmouth South–Eastern Passage",
  4: "Cole Harbour–Westphal",
  5: "Dartmouth Centre",
  6: "Harbourview–Burnside–Dartmouth East",
  7: "Halifax South Downtown",
  8: "Halifax Peninsula North",
  9: "Halifax West Armdale",
  10: "Halifax–Bedford Basin West",
  11: "Spryfield–Sambro Loop–Prospect Road",
  12: "Timberlea–Beechville–Clayton Park–Wedgewood",
  13: "Hammonds Plains–St. Margarets",
  14: "Middle/Upper Sackville–Beaver Bank–Lucasville",
  15: "Lower Sackville",
  16: "Bedford–Wentworth",
};

export const wardOf = (district) => (district ? String(district).replace(/\D+/g, "") : "");

// ---- shared vocabulary -------------------------------------------------
// Duplicated from constants.js on purpose: this bundle must not import from the
// server. Divergence here is the classic bug, so keep them in step.

export const CATEGORY_LABELS = {
  pothole: "Pothole", blocked_driveway: "Blocked driveway", street_light: "Street light",
  tree_hazard: "Tree hazard", sidewalk: "Sidewalk", flooding: "Flooding",
  debris: "Debris", signage: "Signage", graffiti: "Graffiti", other: "Other",
};

// Colour is never decorative here. It encodes severity, status, or a deficit.
export const SEV = {
  low: { label: "Can wait", c: "var(--sev-low)", rank: 0 },
  medium: { label: "Soon", c: "var(--sev-mod)", rank: 1 },
  high: { label: "Safety risk", c: "var(--sev-high)", rank: 2 },
};

export const STATUS = {
  new: { label: "New", c: "var(--status-new)" },
  acknowledged: { label: "Acknowledged", c: "var(--status-ack)" },
  assigned: { label: "Crew assigned", c: "var(--status-ack)" },
  resolved: { label: "Resolved", c: "var(--status-res)" },
};

export const STATUS_ORDER = ["new", "acknowledged", "assigned", "resolved"];

export const clock = (iso) =>
  new Date(iso)
    .toLocaleTimeString("en-CA", { hour: "numeric", minute: "2-digit", hour12: true })
    .toLowerCase()
    // en-CA renders "p.m."; the design sets these as "pm".
    .replace(/\./g, "")
    .replace(/\s+/g, " ");

export const ago = (iso) => {
  const m = Math.floor((Date.now() - new Date(iso)) / 60000);
  if (m < 1) return "just now";
  if (m < 60) return `${m} min ago`;
  const h = Math.round(m / 60);
  if (h < 24) return `${h} ${h === 1 ? "hour" : "hours"} ago`;
  const d = Math.round(h / 24);
  return `${d} ${d === 1 ? "day" : "days"} ago`;
};
