// Street -> coordinates, built from real HRM service request locations.
// streets.json is generated by scripts/pull-data.js: each entry is the median
// lat/lng of every real request on that street and its most common district.
//
// This is a lookup, not general address resolution. An unmatched location is
// stored with null coordinates and shown as "location not mapped" rather than
// dropped or guessed.
import { readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const FILE = join(dirname(fileURLToPath(import.meta.url)), "data", "streets.json");

let streets = [];
try {
  if (existsSync(FILE)) streets = JSON.parse(readFileSync(FILE, "utf8"));
} catch (e) {
  console.error(`geocode: could not load streets.json: ${e.message}`);
}
// Longest names first so "north street" beats a bare "north".
streets.sort((a, b) => b.match.length - a.match.length);
console.log(`geocode: ${streets.length} Halifax streets loaded`);

const NOT_FOUND = { lat: null, lng: null, district: null, geocode_method: "none" };

export function geocode(locationText) {
  if (!locationText) return NOT_FOUND;
  const q = locationText.toLowerCase().replace(/\s+/g, " ").trim();

  // Try the full street name, then the same name with the type word dropped
  // ("north street" also matches a stored "north st").
  const hit =
    streets.find((s) => q.includes(s.match)) ??
    streets.find((s) => q.includes(s.match.replace(/\s(st|rd|ave|dr|blvd|cres|way|ln|crt)$/, "")));

  if (!hit) return NOT_FOUND;
  return { lat: hit.lat, lng: hit.lng, district: hit.district, geocode_method: "lookup" };
}

export const streetCount = () => streets.length;
